'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';

const POSITIONS=[[-.05,0,-1.8],[-2.8,0,-.1],[2.8,0,-.1],[0,0,1.76]];
const SKINS=[0xb57443,0x435e70,0x819786,0x856d80];
const COATS=[0x263a36,0x2c3041,0x233c35,0x332e40];

export default function TableScene({players,activeId,phase}) {
  const host=useRef(null),state=useRef({players,activeId,phase});const [ready,setReady]=useState(false);state.current={players,activeId,phase};
  useEffect(()=>{
    const el=host.current;let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return;}
    renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.35));renderer.outputColorSpace=T.SRGBColorSpace;
    const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,60),baseCamera=new T.Vector3(0,5.9,8.8),lookAt=new T.Vector3(0,1.05,0);camera.position.copy(baseCamera);camera.lookAt(lookAt);
    scene.add(new T.HemisphereLight(0xb8d4cf,0x172823,2));const warm=new T.DirectionalLight(0xffd295,3);warm.position.set(-3,6,3);scene.add(warm);const rim=new T.DirectionalLight(0x66b8b3,2);rim.position.set(4,3,-3);scene.add(rim);
    const material=(color,metalness=0)=>new T.MeshStandardMaterial({color,roughness:.72,metalness,flatShading:true});const wood=material(0x443329),gold=material(0xa88951,.45),felt=material(0x234b40),dark=material(0x142821);
    function mesh(geo,mat,parent,x=0,y=0,z=0){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m;}
    const table=new T.Group();scene.add(table);const base=mesh(new T.CylinderGeometry(3.15,3.1,.22,64),wood,table,0,.33,0);base.scale.z=.57;const edge=mesh(new T.CylinderGeometry(3.09,3.09,.045,64),gold,table,0,.46,0);edge.scale.z=.57;const top=mesh(new T.CylinderGeometry(2.99,2.99,.045,64),felt,table,0,.49,0);top.scale.z=.56;for(const x of [-2,2])mesh(new T.CylinderGeometry(.1,.16,1.1,8),dark,table,x,-.2,0);
    const figures=[];
    for(let i=0;i<4;i++){
      const kind=state.current.players[i]?.character??i,g=new T.Group();g.position.set(...POSITIONS[i]);g.scale.setScalar(i===3?1.32:1.2);g.rotation.y=i===1?.55:i===2?-.55:i===3?Math.PI:0;scene.add(g);
      const skin=material(SKINS[kind%4]),coat=material(COATS[kind%4]),cream=material(0xe0c293);const body=mesh(new T.CylinderGeometry(.29,.48,.72,7),coat,g,0,.72,0);const head=mesh(kind===2?new T.BoxGeometry(.5,.5,.4):new T.IcosahedronGeometry(.34,0),skin,g,0,1.3,0);
      if(kind===0){for(const x of [-.2,.2]){const ear=mesh(new T.ConeGeometry(.13,.37,3),skin,g,x,1.63,0);ear.rotation.z=x>0?-.2:.2;}const snout=mesh(new T.ConeGeometry(.18,.28,4),cream,g,0,1.22,.29);snout.rotation.x=Math.PI/2;}if(kind===1){const beak=mesh(new T.ConeGeometry(.14,.38,4),gold,g,0,1.23,.3);beak.rotation.x=Math.PI/2;}
      for(const x of [-.13,.13])mesh(new T.BoxGeometry(.1,.035,.035),cream,g,x,1.36,.29);const tie=mesh(new T.ConeGeometry(.065,.3,3),gold,g,0,.8,.27);tie.rotation.z=Math.PI;
      const arms=[];for(const x of [-.36,.36]){const arm=mesh(new T.CylinderGeometry(.1,.12,.55,6),coat,g,x,.69,.23);arm.rotation.x=-.7;const hand=mesh(new T.IcosahedronGeometry(.12,0),skin,g,x,.49,.43);arms.push({arm,hand,side:Math.sign(x)});}
      const halo=mesh(new T.TorusGeometry(.45,.016,5,36),gold,g,0,1.29,-.2),cards=new T.Group();cards.position.set(0,.57,.72);g.add(cards);for(let c=0;c<5;c++){const card=mesh(new T.BoxGeometry(.18,.26,.018),material(0xd8caa6),cards,(c-2)*.11,Math.abs(c-2)*.025,0);card.rotation.z=(c-2)*-.11;}
      const hammer=new T.Group();hammer.visible=false;hammer.position.set(POSITIONS[i][0],3.55,POSITIONS[i][2]);scene.add(hammer);const handle=mesh(new T.CylinderGeometry(.07,.085,1.4,8),material(0x6e4527),hammer,0,.68,0);handle.rotation.z=.12;const headGroup=new T.Group();headGroup.position.set(.08,1.38,0);hammer.add(headGroup);const hammerHead=mesh(new T.CylinderGeometry(.44,.52,1.45,10),material(0x817b70,.65),headGroup),rubber=mesh(new T.CylinderGeometry(.49,.55,1.5,10),material(0xc78462),headGroup);hammerHead.rotation.z=Math.PI/2;rubber.rotation.z=Math.PI/2;rubber.visible=false;
      const debris=new T.Group();debris.visible=false;debris.position.set(...POSITIONS[i]);scene.add(debris);const shards=[];for(let d=0;d<13;d++){const shard=mesh(new T.TetrahedronGeometry(.11+(d%3)*.025,0),d%3?coat:skin,debris,0,.55,0);shards.push({shard,angle:d/13*Math.PI*2,speed:.6+(d%5)*.15,lift:.45+(d%4)*.18});}
      figures.push({g,body,head,halo,arms,cards,hammer,hammerHead,rubber,debris,shards,baseY:g.position.y,baseZ:g.position.z,baseScale:i===3?1.32:1.2,idle:0,idleAt:9000+i*1300});
    }
    for(const x of [-1.8,1.8]){mesh(new T.CylinderGeometry(.1,.14,.3,8),gold,table,x,.68,-.7);mesh(new T.SphereGeometry(.055,8,6),new T.MeshBasicMaterial({color:0xffd499}),table,x,.87,-.7);}el.appendChild(renderer.domElement);setReady(true);
    const lost=e=>{e.preventDefault();setReady(false);},restored=()=>setReady(true);renderer.domElement.addEventListener('webglcontextlost',lost);renderer.domElement.addEventListener('webglcontextrestored',restored);
    const project=point=>{point.project(camera);return{x:(point.x+1)*el.clientWidth/2,y:(1-point.y)*el.clientHeight/2};};
    function placeLabels(){scene.updateMatrixWorld();camera.updateMatrixWorld();figures.slice(0,3).forEach((f,i)=>{const label=el.parentElement.querySelector(`.seat-${i}`);if(!label)return;const p=project(f.g.localToWorld(new T.Vector3(0,1.95,0)));label.style.left=`${Math.max(4,Math.min(el.clientWidth-label.offsetWidth,p.x-label.offsetWidth/2))}px`;label.style.top=`${Math.max(0,p.y-48)}px`;label.style.right='auto';});const center=el.parentElement.querySelector('.orbit-table-center');if(center){const p=project(new T.Vector3(0,.52,.1));center.style.top=`${p.y-58}px`;}}
    const resize=()=>{const{width,height}=el.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/Math.max(1,height);baseCamera.z=width<600?10.7:8.8;camera.position.copy(baseCamera);camera.zoom=width<600?1:1.42;camera.updateProjectionMatrix();placeLabels();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
    const media=matchMedia('(prefers-reduced-motion: reduce)');let last=0,signature='',lastPhase=state.current.phase,phaseAt=0;
    renderer.setAnimationLoop(time=>{if(document.hidden||time-last<33)return;last=time;const nextSignature=state.current.players.map(p=>`${p.id}:${p.alive}:${p.count}`).join(',')+state.current.activeId+state.current.phase+el.clientWidth;if(media.matches&&signature===nextSignature)return;signature=nextSignature;if(lastPhase!==state.current.phase){lastPhase=state.current.phase;phaseAt=time;}
      const consequence=['loading','armed','firing','resolved','finished'].includes(state.current.phase),progress=Math.max(0,(time-phaseAt)/1000),targetIndex=figures.findIndex((_,i)=>state.current.players[i]?.id===state.current.activeId),targetPos=targetIndex>=0?POSITIONS[targetIndex]:[0,0,0],focus=consequence&&!media.matches?1:0,targetCamera=new T.Vector3(targetPos[0]*.28,5.15,7.1+targetPos[2]*.12),targetLook=new T.Vector3(targetPos[0]*.42,1.15,targetPos[2]*.52);camera.position.lerp(focus?targetCamera:baseCamera,.055);lookAt.lerp(focus?targetLook:new T.Vector3(0,1.05,0),.055);camera.lookAt(lookAt);
      figures.forEach((f,i)=>{const p=state.current.players[i],active=p?.id===state.current.activeId,targeted=active&&consequence,dead=p?.alive===false;if(time>f.idleAt){f.idle=(f.idle+1+((time/1000+i)|0))%6;f.idleAt=time+10000+((i*1700+time)%5000);}const idle=media.matches?0:Math.sin(time*.0014+i),gesture=media.matches?0:Math.sin(time*.003+i);
        f.hammer.visible=targeted;f.rubber.visible=targeted&&!dead;f.hammerHead.visible=targeted&&dead;let hammerY=3.55,hammerRot=-.16;if(targeted&&(state.current.phase==='loading'||state.current.phase==='armed')){hammerY=3.55-Math.min(1,progress)*.35;hammerRot=-.16+Math.sin(time*.006)*.025;}if(targeted&&state.current.phase==='firing'){hammerY=3.2+Math.sin(time*.018)*.025;}if(targeted&&(state.current.phase==='resolved'||state.current.phase==='finished')){const fall=Math.min(1,progress/.42);hammerY=3.2-2.18*Math.pow(fall,3);if(!dead&&progress>.42)hammerY=1.02+Math.sin(Math.min(1,(progress-.42)/.72)*Math.PI)*1.7;hammerRot=-.16+fall*.1;}f.hammer.position.y=hammerY;f.hammer.rotation.z=hammerRot;
        const hit=targeted&&(state.current.phase==='finished'||(state.current.phase==='resolved'&&progress>.4));f.debris.visible=dead&&(hit||!targeted);f.g.visible=!dead||(targeted&&!hit);if(f.debris.visible)f.shards.forEach((s,d)=>{const spread=targeted?Math.min(1.25,Math.max(0,progress-.4)):1.1;s.shard.position.x=Math.cos(s.angle)*s.speed*spread;s.shard.position.z=Math.sin(s.angle)*s.speed*.55*spread;s.shard.position.y=Math.max(.02,s.lift+Math.sin(Math.min(1,spread)*Math.PI)*s.lift);s.shard.rotation.set(spread*(d+1),spread*d*.7,spread*d*.3);});
        const squash=targeted&&!dead&&hit?Math.max(0,Math.sin(Math.min(1,(progress-.4)/.8)*Math.PI)):0;f.g.scale.set(f.baseScale*(1+squash*.28),f.baseScale*(1-squash*.5),f.baseScale*(1+squash*.18));f.g.position.y=f.baseY+(f.idle===3?idle*.018:0);f.g.position.z=f.baseZ+(f.idle===4?idle*.012:0);f.halo.visible=active&&!dead;f.halo.scale.setScalar(active&&!media.matches?1.12+Math.sin(time*.006)*.035:1);f.head.rotation.z=f.idle===1?gesture*.07:f.idle===5?Math.max(0,gesture)*.08:idle*.018;f.body.rotation.z=f.idle===2?idle*.025:0;f.cards.rotation.y=f.idle===4?gesture*.06:0;f.arms.forEach(({arm,hand,side})=>{const tap=f.idle===3?Math.max(0,gesture)*.12:0;arm.rotation.x=-.7-tap+(active?.08:0);arm.rotation.z=(f.idle===2?gesture*.08:0)*side;hand.position.y=.49+tap*.25;hand.position.x=side*.36;hand.position.z=.43+tap*.18;});
      });placeLabels();renderer.render(scene,camera);
    });
    return()=>{observer.disconnect();renderer.setAnimationLoop(null);renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.domElement.removeEventListener('webglcontextrestored',restored);scene.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});renderer.dispose();renderer.domElement.remove();};
  },[]);return <div className={`orbit-scene ${ready?'is-ready':''}`} ref={host} aria-hidden="true"/>;
}
