'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';

const POSITIONS=[[-2.52,0,-.3],[0,0,-1.76],[2.52,0,-.3],[1.55,0,1.02]];
const SKINS=[0xb57443,0x435e70,0x819786,0x856d80];
const COATS=[0x263a36,0x2c3041,0x233c35,0x332e40];

export default function TableScene({players,activeId,phase,gameKey}) {
  const host=useRef(null),state=useRef({players,activeId,phase});const [ready,setReady]=useState(false);state.current={players,activeId,phase};
  useEffect(()=>{
    const positions=POSITIONS;
    const el=host.current;let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return;}
    renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.35));renderer.outputColorSpace=T.SRGBColorSpace;
    const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,60),baseCamera=new T.Vector3(0,5.9,8.8),lookAt=new T.Vector3(0,1.05,0);camera.position.copy(baseCamera);camera.lookAt(lookAt);
    scene.add(new T.HemisphereLight(0xb8d4cf,0x172823,1.15));const warm=new T.DirectionalLight(0xffd295,1.85);warm.position.set(-3,6,3);scene.add(warm);const rim=new T.DirectionalLight(0x66b8b3,1.35);rim.position.set(4,3,-3);scene.add(rim);const turnTarget=new T.Object3D();scene.add(turnTarget);const turnSpot=new T.SpotLight(0xffd38a,0,9,Math.PI/5.7,.34,1.15);turnSpot.position.set(0,5.8,0);turnSpot.target=turnTarget;scene.add(turnSpot);const faceLight=new T.PointLight(0xffc970,0,2.8,1.6);scene.add(faceLight);const beamMaterial=new T.MeshBasicMaterial({color:0xffd891,transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending});const turnBeam=new T.Mesh(new T.ConeGeometry(1.18,5.15,32,1,true),beamMaterial);turnBeam.position.y=3.08;scene.add(turnBeam);const poolMaterial=new T.MeshBasicMaterial({color:0xffcf78,transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending});const lightPool=new T.Mesh(new T.CircleGeometry(1.08,48),poolMaterial);lightPool.rotation.x=-Math.PI/2;lightPool.position.y=.53;scene.add(lightPool);
    const material=(color,metalness=0)=>new T.MeshStandardMaterial({color,roughness:.72,metalness,flatShading:true});const wood=material(0x443329),gold=material(0xa88951,.45),felt=material(0x234b40),dark=material(0x142821);
    function mesh(geo,mat,parent,x=0,y=0,z=0){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m;}
    const table=new T.Group();scene.add(table);const base=mesh(new T.CylinderGeometry(3.15,3.1,.22,64),wood,table,0,.33,0);base.scale.z=.57;const edge=mesh(new T.CylinderGeometry(3.09,3.09,.045,64),gold,table,0,.46,0);edge.scale.z=.57;const top=mesh(new T.CylinderGeometry(2.99,2.99,.045,64),felt,table,0,.49,0);top.scale.z=.56;for(const x of [-2,2])mesh(new T.CylinderGeometry(.1,.16,1.1,8),dark,table,x,-.2,0);
    const figures=[];
    for(let i=0;i<4;i++){
      const kind=state.current.players[i]?.character??i,g=new T.Group();g.position.set(...positions[i]);g.scale.setScalar(i===3?1.32:1.2);g.rotation.y=Math.atan2(-positions[i][0],-positions[i][2]);scene.add(g);
      const skin=material(SKINS[kind%4]),coat=material(COATS[kind%4]),cream=material(0xe0c293);const body=mesh(new T.CylinderGeometry(.29,.48,.72,7),coat,g,0,.72,0);const head=mesh(kind===2?new T.BoxGeometry(.5,.5,.4):new T.IcosahedronGeometry(.34,0),skin,g,0,1.3,0);
      if(kind===0){for(const x of [-.2,.2]){const ear=mesh(new T.ConeGeometry(.13,.37,3),skin,g,x,1.63,0);ear.rotation.z=x>0?-.2:.2;}const snout=mesh(new T.ConeGeometry(.18,.28,4),cream,g,0,1.22,.29);snout.rotation.x=Math.PI/2;}if(kind===1){const beak=mesh(new T.ConeGeometry(.14,.38,4),gold,g,0,1.23,.3);beak.rotation.x=Math.PI/2;}
      for(const x of [-.13,.13])mesh(new T.BoxGeometry(.1,.035,.035),cream,g,x,1.36,.29);const tie=mesh(new T.ConeGeometry(.065,.3,3),gold,g,0,.8,.27);tie.rotation.z=Math.PI;
      const arms=[];for(const x of [-.36,.36]){const arm=mesh(new T.CylinderGeometry(.1,.12,.55,6),coat,g,x,.69,.23);arm.rotation.x=-.7;const hand=mesh(new T.IcosahedronGeometry(.12,0),skin,g,x,.49,.43);arms.push({arm,hand,side:Math.sign(x)});}
      const halo=mesh(new T.TorusGeometry(.45,.016,5,36),gold,g,0,1.29,-.2),cards=new T.Group();cards.position.set(0,.57,.72);g.add(cards);for(let c=0;c<5;c++){const card=mesh(new T.BoxGeometry(.18,.26,.018),material(0xd8caa6),cards,(c-2)*.11,Math.abs(c-2)*.025,0);card.rotation.z=(c-2)*-.11;}
      const outward=new T.Vector2(positions[i][0],positions[i][2]).normalize(),hammer=new T.Group();hammer.visible=false;hammer.position.set(positions[i][0]+outward.x*.12,3.28,positions[i][2]+outward.y*.12);hammer.rotation.y=Math.atan2(outward.x,outward.y);scene.add(hammer);const swingPivot=new T.Group();swingPivot.rotation.x=1.34;hammer.add(swingPivot);const handle=mesh(new T.CylinderGeometry(.085,.105,1.95,10),material(0x6e4527),swingPivot,0,-.96,0);const headGroup=new T.Group();headGroup.position.set(0,-1.98,0);swingPivot.add(headGroup);const hammerHead=mesh(new T.CylinderGeometry(.5,.55,1.5,14),material(0x817b70,.65),headGroup),rubber=mesh(new T.CylinderGeometry(.55,.6,1.56,14),material(0xc78462),headGroup);hammerHead.rotation.x=Math.PI/2;rubber.rotation.x=Math.PI/2;rubber.visible=false;
      const debris=new T.Group();debris.visible=false;debris.position.set(...positions[i]);scene.add(debris);const shards=[];for(let d=0;d<13;d++){const shard=mesh(new T.TetrahedronGeometry(.11+(d%3)*.025,0),d%3?coat:skin,debris,0,.55,0);shards.push({shard,angle:d/13*Math.PI*2,speed:.6+(d%5)*.15,lift:.45+(d%4)*.18});}
      figures.push({g,body,head,halo,arms,cards,hammer,swingPivot,hammerHead,rubber,debris,shards,hammerBase:hammer.position.clone(),baseY:g.position.y,baseZ:g.position.z,baseScale:i===3?1.32:1.2,idle:0,idleAt:9000+i*1300});
    }
    for(const x of [-1.8,1.8]){mesh(new T.CylinderGeometry(.1,.14,.3,8),gold,table,x,.68,-.7);mesh(new T.SphereGeometry(.055,8,6),new T.MeshBasicMaterial({color:0xffd499}),table,x,.87,-.7);}el.appendChild(renderer.domElement);setReady(true);
    const lost=e=>{e.preventDefault();setReady(false);},restored=()=>setReady(true);renderer.domElement.addEventListener('webglcontextlost',lost);renderer.domElement.addEventListener('webglcontextrestored',restored);
    const project=point=>{point.project(camera);return{x:(point.x+1)*el.clientWidth/2,y:(1-point.y)*el.clientHeight/2};};
    function placeLabels(){scene.updateMatrixWorld();camera.updateMatrixWorld();figures.slice(0,3).forEach((f,i)=>{const label=el.parentElement.querySelector(`.seat-${i}`);if(!label)return;const p=project(f.g.localToWorld(new T.Vector3(0,1.95,0)));label.style.left=`${Math.max(4,Math.min(el.clientWidth-label.offsetWidth,p.x-label.offsetWidth/2))}px`;label.style.top=`${Math.max(0,p.y-48)}px`;label.style.right='auto';});const center=el.parentElement.querySelector('.orbit-table-center');if(center){const p=project(new T.Vector3(0,.52,.1));center.style.top=`${p.y-58}px`;}}
    const resize=()=>{const{width,height}=el.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/Math.max(1,height);baseCamera.z=width<600?10.7:8.8;camera.position.copy(baseCamera);camera.zoom=width<600?1:1.42;camera.updateProjectionMatrix();placeLabels();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
    const media=matchMedia('(prefers-reduced-motion: reduce)');let last=0,signature='',lastPhase=state.current.phase,phaseAt=0;
    renderer.setAnimationLoop(time=>{if(document.hidden||time-last<33)return;last=time;const nextSignature=state.current.players.map(p=>p?`${p.id}:${p.alive}:${p.count}`:'open').join(',')+state.current.activeId+state.current.phase+el.clientWidth;if(media.matches&&signature===nextSignature)return;signature=nextSignature;if(lastPhase!==state.current.phase){lastPhase=state.current.phase;phaseAt=time;}
      const consequence=['loading','armed','firing','resolved','finished'].includes(state.current.phase),progress=Math.max(0,(time-phaseAt)/1000),targetIndex=figures.findIndex((_,i)=>state.current.players[i]?.id===state.current.activeId),targetPos=targetIndex>=0?positions[targetIndex]:[0,0,0],turnLit=state.current.phase==='playing'&&targetIndex>=0,focus=consequence&&!media.matches?1:0,targetCamera=new T.Vector3(targetPos[0]*.32,4.72,6.72+targetPos[2]*.12),targetLook=new T.Vector3(targetPos[0]*.48,1.18,targetPos[2]*.52);camera.position.lerp(focus?targetCamera:baseCamera,.045);lookAt.lerp(focus?targetLook:new T.Vector3(0,1.05,0),.055);camera.lookAt(lookAt);const turnIntensity=turnLit?(media.matches?11:28):0;turnSpot.intensity+=(turnIntensity-turnSpot.intensity)*.1;turnSpot.position.lerp(new T.Vector3(targetPos[0],5.85,targetPos[2]+.18),.12);turnTarget.position.lerp(new T.Vector3(targetPos[0],.85,targetPos[2]),.12);faceLight.intensity+=(turnLit?(media.matches?3:8)-faceLight.intensity:-faceLight.intensity)*.12;faceLight.position.lerp(new T.Vector3(targetPos[0],1.72,targetPos[2]+.35),.15);turnBeam.visible=turnLit;lightPool.visible=turnLit;beamMaterial.opacity+=(turnLit?(media.matches?.08:.19)-beamMaterial.opacity:-beamMaterial.opacity)*.1;poolMaterial.opacity+=(turnLit?(media.matches?.12:.28)-poolMaterial.opacity:-poolMaterial.opacity)*.1;turnBeam.position.x=turnTarget.position.x;turnBeam.position.z=turnTarget.position.z;lightPool.position.x=turnTarget.position.x;lightPool.position.z=turnTarget.position.z;
      figures.forEach((f,i)=>{const p=state.current.players[i];if(!p){f.g.visible=false;f.hammer.visible=false;f.debris.visible=false;return;}const active=p.id===state.current.activeId,targeted=active&&consequence,dead=p.alive===false;if(time>f.idleAt){f.idle=(f.idle+1+((time/1000+i)|0))%6;f.idleAt=time+10000+((i*1700+time)%5000);}const idle=media.matches?0:Math.sin(time*.0014+i),gesture=media.matches?0:Math.sin(time*.003+i);
        f.hammer.visible=targeted;f.rubber.visible=targeted&&!dead;f.hammerHead.visible=targeted&&dead;let hammerRot=1.34,lift=0;if(targeted&&(state.current.phase==='loading'||state.current.phase==='armed')){const wind=Math.sin(Math.min(1,progress)*Math.PI/2);hammerRot=1.34+wind*.16;lift=wind*.24;}if(targeted&&state.current.phase==='firing'){hammerRot=1.5;lift=.24;}if(targeted&&(state.current.phase==='resolved'||state.current.phase==='finished')){const swing=Math.min(1,progress/.5),ease=1-Math.pow(1-swing,4);hammerRot=1.5-1.5*ease;lift=.24*(1-ease);if(!dead&&progress>.5){const bounce=Math.sin(Math.min(1,(progress-.5)/.7)*Math.PI);hammerRot=bounce*.78;lift=bounce*.1;}}f.hammer.position.copy(f.hammerBase);f.hammer.position.y+=lift;f.swingPivot.rotation.x=hammerRot;
        const hit=targeted&&(state.current.phase==='finished'||(state.current.phase==='resolved'&&progress>.4));f.debris.visible=dead&&(hit||!targeted);f.g.visible=!dead||(targeted&&!hit);if(f.debris.visible)f.shards.forEach((s,d)=>{const spread=targeted?Math.min(1.25,Math.max(0,progress-.4)):1.1;s.shard.position.x=Math.cos(s.angle)*s.speed*spread;s.shard.position.z=Math.sin(s.angle)*s.speed*.55*spread;s.shard.position.y=Math.max(.02,s.lift+Math.sin(Math.min(1,spread)*Math.PI)*s.lift);s.shard.rotation.set(spread*(d+1),spread*d*.7,spread*d*.3);});
        const squash=targeted&&!dead&&hit?Math.max(0,Math.sin(Math.min(1,(progress-.4)/.8)*Math.PI)):0,activeBoost=active&&!media.matches?1.1:1;f.g.scale.set(f.baseScale*activeBoost*(1+squash*.28),f.baseScale*activeBoost*(1-squash*.5),f.baseScale*activeBoost*(1+squash*.18));f.g.position.y=f.baseY+(f.idle===3?idle*.018:0);f.g.position.z=f.baseZ+(f.idle===4?idle*.012:0);f.halo.visible=(i===3||active)&&!dead;f.halo.scale.setScalar(active&&!media.matches?1.12+Math.sin(time*.006)*.035:i===3?.86:1);f.head.rotation.z=f.idle===1?gesture*.07:f.idle===5?Math.max(0,gesture)*.08:idle*.018;f.body.rotation.z=f.idle===2?idle*.025:0;f.cards.rotation.y=f.idle===4?gesture*.06:0;f.arms.forEach(({arm,hand,side})=>{const tap=f.idle===3?Math.max(0,gesture)*.12:0;arm.rotation.x=-.7-tap+(active?.08:0);arm.rotation.z=(f.idle===2?gesture*.08:0)*side;hand.position.y=.49+tap*.25;hand.position.x=side*.36;hand.position.z=.43+tap*.18;});
      });placeLabels();renderer.render(scene,camera);
    });
    return()=>{observer.disconnect();renderer.setAnimationLoop(null);renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.domElement.removeEventListener('webglcontextrestored',restored);scene.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});renderer.dispose();renderer.domElement.remove();};
  },[gameKey]);return <div className={`orbit-scene ${ready?'is-ready':''}`} ref={host} aria-hidden="true"/>;
}
